services:
  - type: web
    name: yougame
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production